### ISSUE TITLE
Add configuration option for filtered logs

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-messagebus#24]
0.0.4 added a hard-coded list of message types to exclude from logging. This should support specifying a list of message types in configuration with the current list as the default value

              This should probably come from configuration. Could be an issue for later

_Originally posted by @NeonDaniel in https://github.com/OpenVoiceOS/ovos-messagebus/pull/23#discussion_r1438455744_

**Comment by JarbasAl** [comment]
closed by #29
