### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by generallynonsensical** [OpenVoiceOS/ovos-messagebus#7]
Installed `ovos-messagebus` via pip. Tried both the latest 0.0.2 and 0.0.2a6 and both return the same error:

`Traceback (most recent call last):
  File "/home/gaia/.local/bin/ovos-messagebus", line 5, in <module>
    from ovos_messagebus.__main__ import main
ModuleNotFoundError: No module named 'ovos_messagebus'`

**Comment by JarbasAl** [comment]
0.0.3a1 (current dev branch) has this fixed

**Comment by generallynonsensical** [comment]
Still learning to properly navigate git. Can't see where to check for the dev branch version. 

ovos-messagebus is in the dev branch by default for me in github, but when I check the changelog, it says only 0.0.2 is available.
